version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: php:8.1.12-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./storage/:/mnt/host/d/projects/learn/webinar2/storage/
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage/:${PROJECT_PATH}/storage/
  db:
      image: mysql
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      environment:
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      ports:
          - "4006:3306"
      volumes:
          - ./docker/mysql/data:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
          PMA_HOST: ${DB_HOST}
          PMA_PORT: ${DB_PORT}
      ports:
          - "${PMA_PORT}:80"
